services:
  glance:
    image: glanceapp/glance:${VERSION}
    container_name: glance
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/app/config
      - ./assets:/app/assets
      - ./widget:/app/widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home:/home:ro
    healthcheck:
      test: wget --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - homelab_common
    # ports:
    #   - 8080:8080

networks:
  homelab_common:
    external: true
