services:
  glance:
    container_name: glance
    image: glanceapp/glance:${VERSION}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/app/config
      - ./assets:/app/assets
      - ./widget:/app/widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home:/home:ro
    networks:
      - homelab_common

networks:
  homelab_common:
    external: true
