services:
  netbird-client:
    image: netbirdio/netbird:${VERSION}
    container_name: netbird-client
    hostname: homelab
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      NB_SETUP_KEY: ${NB_SETUP_KEY}
      NB_MANAGEMENT_URL: ${NB_MANAGEMENT_URL}
    volumes:
      - netbird-client:/var/lib/netbird

volumes:
  netbird-client:
    name: netbird-client
