services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${VERSION}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - homelab_infrastructure

volumes:
  portainer_data:

networks:
  homelab_infrastructure:
    external: true
