services:
  papra:
    image: ghcr.io/papra-hq/papra:${VERSION}-rootless
    container_name: papra
    restart: unless-stopped
    user: 1000:1000
    env_file:
      - .env
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
    volumes:
      - ${APP_DATA}:/app/app-data
    networks:
      - homelab_media
    ports:
      - 1221:1221

networks:
  homelab_media:
    external: true
