services:
  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:${VERSION}'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: curl -f http://localhost:81/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - homelab_infrastructure
      - homelab_media
      - homelab_monitoring
      - homelab_networking
      - homelab_security
      - homelab_tool
    ports:
      - '80:80'
      - '443:443'

networks:
  homelab_infrastructure:
    external: true
  homelab_media:
    external: true
  homelab_monitoring:
    external: true
  homelab_networking:
    external: true
  homelab_security:
    external: true
  homelab_tool:
    external: true
