services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${VERSION}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      # DNS Ports
      - '${PIHOLE_BIND_IP}:53:53/tcp'
      - '${PIHOLE_BIND_IP}:53:53/udp'
    environment:
      TZ: 'Europe/Helsinki'
      FTLCONF_webserver_api_password: '${PIHOLE_WEBSERVER_API_PASSWORD}'
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_upstreams: '1.1.1.1;8.8.8.8'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      - homelab_networking

networks:
  homelab_networking:
    external: true
