services:
  pihole:
    image: pihole/pihole:${VERSION}
    container_name: pihole
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: 'Europe/Helsinki'
      FTLCONF_webserver_api_password: '${PIHOLE_WEBSERVER_API_PASSWORD}'
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_upstreams: '1.1.1.1;8.8.8.8'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    healthcheck:
      test: curl -f http://localhost:80/admin/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - homelab_networking
    ports:
      # DNS Ports
      - '${PIHOLE_BIND_IP}:53:53/tcp'
      - '${PIHOLE_BIND_IP}:53:53/udp'
      # Admin
      # - 80:80

networks:
  homelab_networking:
    external: true
