services:
  uptime-kuma:
    image: louislam/uptime-kuma:${VERSION}
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
    healthcheck:
      test: curl -f http://localhost:3001/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - homelab_monitoring
    ports:
      - 3001:3001

networks:
  homelab_monitoring:
    external: true
