services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:${VERSION}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
    networks:
      - homelab_monitoring

networks:
  homelab_monitoring:
    external: true
