services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:${VERSION}
    container_name: zerobyte
    restart: unless-stopped
    ports:
      - '4096:4096'
    environment:
      - TZ=Europe/Helsinki
      - BASE_URL='$BASE_URL'
      - APP_SECRET='$APP_SECRET' # `openssl rand -hex 32`
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zerobyte:/var/lib/zerobyte
      # read-only
      - /home:/home:ro
      - ${MAIN_1}:/hdd-main:ro
      # read-write
      - ${BACKUP_1}/home-backup:/home-backup
      - ${BACKUP_1}/immich-backup:/immich-backup
      - ${BACKUP_1}/papra-backup:/papra-backup
    networks:
      - homelab_shared

networks:
  homelab_shared:
    external: true
