services:
  dockhand:
    container_name: dockhand
    image: fnsys/dockhand:${VERSION}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dockhand-postgres:5432/${POSTGRES_DB}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    depends_on:
      - dockhand-postgres
    networks:
      - default
      - homelab_infrastructure

  dockhand-postgres:
    container_name: dockhand-postgres
    image: postgres:16-alpine
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dockhand_data:
  postgres_data:

networks:
  homelab_infrastructure:
    external: true
