services:
  dockhand:
    image: fnsys/dockhand:${VERSION}
    container_name: dockhand
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dockhand-postgres:5432/${POSTGRES_DB}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    healthcheck:
      test: curl -f http://localhost:3000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - dockhand-postgres
    networks:
      - default
      - homelab_infrastructure
    # ports:
    #   - 3000:3000

  dockhand-postgres:
    image: postgres:16-alpine
    container_name: dockhand-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  dockhand_data:
  postgres_data:

networks:
  homelab_infrastructure:
    external: true
