- name: Home
  columns:
    - size: small
      widgets:
        - $include: ../widget/default/dns-stats.yaml

        - $include: ../widget/community/uptime-kuma.yaml

    - size: full
      widgets:
        - $include: ../widget/default/search.yaml

        - $include: ../widget/community-refactored/beszel-server-stats.yaml

        - $include: ../widget/default/docker-containers.yaml

    - size: small
      widgets:
        - $include: ../widget/default/weather.yaml

        - $include: ../widget/community-refactored/immich-stats.yaml

        - $include: ../widget/community/papra-stats.yaml

        # - $include: ../widget/default/markets.yaml
