services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VERSION}
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - '${DATA}:/data/'
    security_opt:
      - no-new-privileges:true
    networks:
      - homelab_security

networks:
  homelab_security:
    external: true
